@api = http://localhost:4000/api/users

GET {{api}}/count


###
GET {{api}}/eucogar7@gmail.com


### delete product 
DELETE {{api}}/eucogar7@gmail.com

###
POST {{api}}
Content-Type: application/json

{
    "name": "eulises",
    "lastName": "coronado",
    "city": "Valledupar",
    "phone": "3225359098",
    "email": "eucogar7@gmail.com",
    "password": "119272"
}

//update
###
PUT {{api}}/eucogar7@gmail.com
Content-Type: application/json

{
    "name": "Eulises",
    "lastName": "Garcia",
    "city": "Valledupar",
    "phone": "3225359098",
    "email": "eucogar7@gmail.com",
    "password": "1192729833"
}